PASSED_DATE_INFO_CLASS_NAME = "imspo_mt__cmd"
FUTURE_INFO_CLASS_NAME = "imspo_mt__date"
COMPETITION_CLASS_NAME = "imspo_mt__lg-st-co"
VIDEO_CLASS_NAME = "imspo_mt__ndl-p"
EMPTY_TILE_CLASS_NAME = "liveresults-sports-immersive__empty-tile"
TEAMS_INFO_CLASS_NAME = "liveresults-sports-immersive__hide-element"
WIDGET_CLASS_NAME = "imspo_mt__mtc-no"
RESULTS_INFO_CLASS_NAME = "imspo_mt__t-sc"
SPAN_NAME = ".//span"
YESTERDAY_STR = "yesterday"
TODAY_STR = "today"
DATE_FORMAT_STR = '%d %b %y'
LEAGUE_DATA_JSON_PATH = "TeamsPerformance/static/league_data.json"
SEE_MORE_NOT_LOCAL_LEAGUES_XPATH = "//li[@data-tab_type='LEAGUE_MATCHES']"
SEE_MORE_LOCAL_LEAGUES_XPATH = "//li[@data-tab_type='TEAM_MATCHES']"